apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://download.elastic.co/downloads/eck/2.13.0/crds.yaml # ECK CRDs
  - https://download.elastic.co/downloads/eck/2.13.0/operator.yaml # ECK Operator
  # - networkpolicy-egress.yaml
  # - namespace.yaml
  # - serviceaccount.yaml
  # - role.yaml
  # - rolebinding.yaml
  # - operator.yaml
