apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - https://download.elastic.co/downloads/eck/2.11.0/crds.yaml # ECK CRDs
  - operator.yaml
  - networkpolicy-egress.yaml
